import type { Metadata } from "next";
import "./globals.css";

import Header from "@/components/custom/organisms/Header";
import Footer from "@/components/custom/organisms/Footer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Neighbourly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          {children}
          <Toaster richColors position="top-right" />
          <Footer />
        </main>
      </body>
    </html>
  );
}
